github: [metadata]
# Default format for permalinks
# see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

# Files to exclude from jekyll build
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
# Markdown providor
markdown: kramdown
# URL of website
url: https://womeninrobotics.org

# Title of the site
title: Women in Robotics
description: Community for women working in robotics, and women who want to work in robotics.
image: https://womeninrobotics.org/assets/images/logo/WiRLogo-banner.png

donation_url: /donate/
store_url: /store/
sponsor_url: mailto:info@womeninrobotics.org
newsletter_url: /newsletter/
join_url: /signup/

# Social media info
facebook: https://www.facebook.com/womeninrobotics
twitter: https://twitter.com/womeninroboticz/
instagram: https://www.instagram.com/womeninroboticz/
pinterest: https://www.pinterest.com/womeninrobotics
linkedin: https://www.linkedin.com/company/womeninrobotics/
email: info@womeninrobotics.org

# TODO (athackst) rss and atom feeds
# atom_path: TODO
# rss_path: TODO

# google settings
google:
  tracking_id: G-2V4NNSWC1S
#   ad_client: TODO

# TODO (athackst) comment settings
# comments:
#   disqus:
#     short_name:

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - github-pages
  - jekyll-redirect-from # Set up custom redirects
  - jemoji # Github flavored emoji

whitelist:
  - jekyll-redirect-from
