github: [metadata]
# Default format for permalinks
# see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

# Files to exclude from jekyll build
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
# Markdown providor
markdown: kramdown
# URL of website
url: https://womeninrobotics.org

# Title of the site
title: Women in Robotics
description: Community for women working in robotics, and women who want to work in robotics.

donation_url: https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=7QBGVMNX4QMS8
store_url: https://svrobo.org/shop/
sponsor_url: mailto:info@womeninrobotics.org
newsletter_url: https://sendfox.com/womeninrobotics
join_url: /signup/

# TODO (athackst)
# ein_id: TODO

# TODO (athackst) Social media info
facebook: https://www.facebook.com/womeninrobotics
twitter: https://twitter.com/womeninroboticz/
instagram: https://www.instagram.com/womeninroboticz/
pinterest: https://www.pinterest.com/womeninrobotics
linkedin: https://www.linkedin.com/groups/7072127/

# TODO (athackst) rss and atom feeds
# atom_path: TODO
# rss_path: TODO

# TODO (athackst) google settings
google:
  tracking_id: G-2V4NNSWC1S
#   ad_client: TODO

# TODO (athackst) comment settings
# comments:
#   disqus:
#     short_name:
