name: Update JSON file from Google Sheet
author: Allison Thackston
description: "Get a Google Spreadsheet as a JSON file and create a PR"

inputs:
  published_sheet_url:
    description: "The URL of the published Google Spreadsheet"
    required: true
  output_file:
    description: "URI of the output file"
    required: true
  repo_token:
    description: "The GitHub token used to authenticate with the repository"
    default: ${{ github.token }}
  branch_name:
    description: "The name of the branch where the changes will be pushed"
    required: true
    default: "update-json"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get spreadsheet as JSON
      shell: bash
      run: |
        pip install csvkit
        curl -L "${{ inputs.published_sheet_url }}" \
          | csvjson --indent 4 \
          > ${{ inputs.output_file }}
    - name: Check for changes
      shell: bash
      run: |
        git status --porcelain | grep -q . && echo "run_pr=true" >> $GITHUB_OUTPUT || echo "All done"
      id: check_changes
    - name: Add JSON file
      if: steps.check_changes.outputs.run_pr == 'true'
      shell: bash
      run: |
        git config --local user.email "website@womeninrobotics.org"
        git config --local user.name "WIR Website Bot"
        git add ${{ inputs.output_file }}
        git commit -m "Updating ${{ inputs.output_file }}"
    - name: Push changes
      if: steps.check_changes.outputs.run_pr == 'true'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ inputs.repo_token }}
        branch: ${{ inputs.branch_name }}-${{ github.run_number }}
    - name: Create pull request
      if: steps.check_changes.outputs.run_pr == 'true'
      uses: peter-evans/create-pull-request@v5.0.1
      with:
        title: "Update ${{ inputs.output_file }}"
        body: "Updates ${{ inputs.output_file }}"
        branch: ${{ inputs.branch_name }}-${{ github.run_number }}
        base: main
        draft: false
        token: ${{ inputs.repo_token }}
