name: Update JSON file from Google Sheet
author: Allison Thackston
description: "Get a Google Spreadsheet as a JSON file and create a PR"

inputs:
  published_sheet_url:
    description: "The URL of the published Google Spreadsheet"
    required: true
  output_file:
    description: "URI of the output file"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get spreadsheet as JSON
      shell: bash
      run: .github/actions/get-google-sheets-json/get_json.sh
      env:
        SHEET_URL: ${{ inputs.published_sheet_url }}
        OUTPUT_FILE: ${{ inputs.output_file }}
