backend:
  name: git-gateway
  repo: womeninrobotics/womeninrobotics.github.io
  branch: main
  accept_roles:
    - admin
    - editor
local_backend: true
publish_mode: editorial_workflow
logo_url: https://www.womeninrobotics.org/assets/images/logo/WiRLogo-banner.png
media_folder: "assets/images" # Media files will be stored in the repo under images/uploads
collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    preview_path: news
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
  - name: "forms" # Used in routes, e.g., /admin/collections/blog
    label: "Forms" # Used in the UI
    folder: "pages/forms" # The path to the folder where the documents are stored
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "{{permalink}}"
    fields: # The fields for each document, usually in front matterlayout: iframe
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Form", name: "iframe", widget: "string" }
      - { label: "Height", name: "height", widget: "number" }
  - name: "redirects" # Used in routes, e.g., /admin/collections/blog
    label: "Redirects" # Used in the UI
    folder: "pages/redirects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matterlayout: iframe
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Redirect To", name: "redirect_to", widget: "string" }
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "pages/posts" # The path to the folder where the documents are stored
    preview_path: "{{permalink}}"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matterlayout: iframe
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
