backend:
  name: git-gateway
  repo: womeninrobotics/womeninrobotics.github.io
  branch: main
  squash_merges: true
  accept_roles:
    - admin
    - editor
local_backend: true
publish_mode: editorial_workflow
logo_url: https://www.womeninrobotics.org/assets/images/logo/WiRLogo-banner.png
media_folder: "assets/images" # Media files will be stored in the repo under images/uploads
collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    preview_path: news
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - {
          label: "External Link",
          name: "link",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "forms" # Used in routes, e.g., /admin/collections/blog
    label: "Forms" # Used in the UI
    folder: "pages/forms" # The path to the folder where the documents are stored
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "{{permalink}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Form", name: "iframe", widget: "string" }
      - { label: "Height", name: "height", widget: "number" }
  - name: "redirects" # Used in routes, e.g., /admin/collections/blog
    label: "Redirects" # Used in the UI
    folder: "pages/redirects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Redirect To", name: "redirect_to", widget: "string" }
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "pages/posts" # The path to the folder where the documents are stored
    preview_path: "{{permalink}}"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - {
          label: "Layout",
          name: "layout",
          widget: "select",
          options: ["default", "page", "post"],
          default: "post",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "list" # Used in routes, e.g., /admin/collections/blog
    label: "Annual List" # Used in the UI
    folder: "_wir-list" # The path to the folder where the documents are stored
    preview_path: "/wir-list/{{year}}"
    create: true # Allow users to create new documents in this collection
    slug: "YYYY.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Year",
          name: "year",
          widget: "date",
          default: "",
          format: "YYYY",
          date_format: "YYYY",
        }
      - { label: "Robohub link", name: "robohub", widget: "string" }
      - {
          label: "Archive",
          name: "archive",
          widget: "boolean",
          default: "false",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Layout",
          name: "layout",
          widget: "select",
          options: ["list"],
          default: "list",
        }
  - name: "config" # Used in routes, e.g., /admin/collections/blog
    label: "Config" # Used in the UI
    editor:
      preview: false
    files:
      - label: "Nav bar"
        name: "nav-bar"
        file: "_data/nav-bar.yaml"
        fields:
          - label: Pages
            name: pages
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Url, name: url, widget: string }
              - {
                  label: Subpages,
                  name: subpages,
                  widget: list,
                  fields:
                    [
                      { label: Title, name: title, widget: string },
                      { label: Url, name: url, widget: string },
                    ],
                }
      - label: "Stats"
        name: "stats"
        file: "_data/stats.yaml"
        fields:
          - label: "Total Members"
            name: "members"
            widget: "number"
          - label: "Total Subscribers"
            name: "subscribers"
            widget: "number"
          - label: "Total Chapters"
            name: "chapters"
            widget: "number"
      - label: "Sponsors"
        name: "sponsors"
        file: "_data/sponsors.yaml"
        fields:
          - label: "Sponsors"
            name: "companies"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Logo, name: logo, widget: image }
              - { label: Link, name: link, widget: string }
