name: eventbrite

on:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   # Generate from https://crontab.guru/
  #   #        ┌───────────── minute (0 - 59)
  #   #        │ ┌───────────── hour (0 - 23)
  #   #        │ │ ┌───────────── day of the month (1 - 31)
  #   #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #   #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #   #        │ │ │ │ │
  #   #        │ │ │ │ │
  #   #        │ │ │ │ │
  #   #        * * * * *
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  meetingplace:
    runs-on: ubuntu-latest
    name: Update events from eventbrite
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Get chapter events from meetingplace
        run: .github/eventbrite.sh
        env:
          EVENTBRITE_ORG_ID: ${{ secrets.EVENTBRITE_ORG_ID }}
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
      - name: Set up git
        run: |
          git config user.name "WiR Bot"
          git config user.email website@womeninrobotics.org
          git add .
          if ! git diff --exit-code --cached; then
            git commit -m "Updating meetingplace events"
            git push
          fi
