name: Test site
on:
  push:
    branches:
      - main # Run test on every push to main
  pull_request: # Run tests on all pull requests
  workflow_dispatch: # Run tests from manual triggers from any branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3 # Not needed with a .ruby-version file
      - run: bundle install
      - run: bundle exec jekyll build
      - name: HtmlProofer
        run: |
          ruby .github/htmlproofer.rb
